config/routes.rb
Rails.application.routes.draw do
  resources :interview_types
  resources :languages
  resources :appointments
  resources :interviewees
  resources :interviewers
  get '/homepages', to: 'homepages#index', as: 'welcome'
  delete '/sessions/logout_interviewee', to: 'sessions#logout_interviewee', as: 'logout_interviewee'
  get '/sessions/new', to: 'sessions#new', as: 'new_interviewee_login'
  post '/sessions/create', to:'sessions#create', as: 'interviewee_login'
  delete '/sessions/logout_interviewer', to: 'sessions#logout_interviewer', as: 'logout_interviewer'
  get '/sessions/new_int', to: 'sessions#new_int', as: 'new_interviewer_login'
  post '/sessions/create_int', to:'sessions#create_int', as: 'interviewer_login'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/interviewee.rb
class Interviewee < ApplicationRecord
    has_many :appointments
    has_many :interviewers, through: :appointments
    has_many :languages, through: :appointments
    has_secure_password
    validates :username, uniqueness: true
    validates :name, :age, presence: true


    def total_spent
        self.interviewers.sum{|interviewer| interviewer.interview_price}
    end

    def most_popular_language
        if self.appointments.count >= 1
            prog_object = self.languages.max_by(1){|lang| lang.appointments.count}
            prog_object[0].prog_lang
        else
            "NA"
        end
    end

    def most_popular_language_count

        self.languages.count{|lang| lang.appointments if lang.prog_lang == self.most_popular_language}
    end

    def most_popular_interviewer
        if self.appointments.count >= 1
            inter_object = self.interviewers.max_by(1){|interviewer| interviewer.appointments.count}
            inter_object[0].name
        else
            "NA"
        end
    end

    def most_popular_interviewer_count
        self.interviewers.count{|interviewer| interviewer.appointments if interviewer.name == self.most_popular_interviewer}
    end


end

app/controllers/interviewees_controller.rb
class IntervieweesController < ApplicationController
    before_action :find_interviewee, only: [:show, :edit, :update, :destroy]
    skip_before_action :authorize_interviewee, only: [:new, :create]
    #skip_before_action :authorize_interviewer
    

    def index
        @interviewees = Interviewee.all
    end
    
    def show
    end
    
    def new
        @interviewee = Interviewee.new
        @languages = Language.all
    end
    
    def create
        @interviewee = Interviewee.create(interviewee_params)
        if @interviewee.valid?
            session[:interviewee_id] = @interviewee.id
            redirect_to interviewee_path(@interviewee)
        else
            flash[:my_error] = @interviewee.errors.full_messages
            render :new
        end
    end

    def edit
    end
    
    def update
        @interviewee.update(interviewee_params)
        redirect_to interviewee_path(@interviewee)
    end
    
    def destroy
        @interviewee.destroy
        redirect_to welcome_path
    end

    private

    def interviewee_params
        params.require(:interviewee).permit(:name, :age, :username, :password)
    end

    def find_interviewee
        @interviewee = Interviewee.find(params[:id])
    end

end

app/helpers/interviewees_helper.rb
module IntervieweesHelper
end

app/views/interviewees/_form.html.erb
<% if flash[:my_error] %>
    <% flash[:my_error].each do |err| %>
        Error Message: <%= err %><br>
    <% end %>
<% end %>

<div>
<%= bootstrap_form_for(@interviewee, layout: :inline) do |f| %>
    <%= f.text_field :name %> <br>
    <br>
    <%= f.text_field :username %><br>
    <br>
    <%= f.number_field :age %><br>
    <br>
    <%= f.text_field :password %><br>
    <br>
    <button type="submit" class="btn btn-primary mb-2">Submit</button>
    <% end %>
</div>

app/views/interviewees/edit.html.erb
<h1>Interviewee Edit Page</h1>


<%= render "form"%>

app/views/interviewees/index.html.erb
<h1>Interviewee Index Page</h1>

<% @interviewees.each do |interviewee| %>
Name: <%= interviewee.name %><br>
Age: <%= interviewee.age %><br>
<% end %>

app/views/interviewees/new.html.erb
<h1>Interviewee New Page</h1>

<%= render "form"%>

app/views/interviewees/show.html.erb
<h1><%=@interviewee.name%>'s Profile Page</h1>

<h3>Actions</h3>
Update Profile Information: <%= button_to "Edit Profile", edit_interviewee_path(@interviewee), method: :get%><br>

Log-out from Application:<%= button_to "Log-out", logout_interviewee_path(@interviewee), method: :delete%><br>

Delete Profile: <%= button_to "Delete Profile Permanently", interviewee_path(@interviewee), method: :delete%><br> 

<h3>Profile Details</h3>
Name: <%= @interviewee.name %><br>
Age: <%= @interviewee.age %><br>

<h3>Upcoming Interviews</h3>

<%= button_to "View Interviewers", interviewers_path, method: :get %><br>


<%= button_to "Appointment Scheduler", new_appointment_path, method: :get %><br>
<!--Lists upcoming interviews scheduled through interface-->
<% @interviewee.appointments.each do |appt| %>
<h4>Appointment Summary</h4>
    <p>Interview Date: <%= appt.date_clean %></p>
    <p>Interview Type: <%= appt.int_type%></p>
    <p>Interview Difficulty: <%= appt.difficulty %></p>
    <p>Interivew Link/Location: <%= appt.link %></p>
    <p>Interview Notes: <%= appt.note %></p>
<% end %>

<h3>Total Money Spent To Date:</h3>
<!--Total money spent on interviews through the site-->
$ <%= @interviewee.total_spent %><br>


<h3>Coding Language of Choice:</h3>
<!-- Shows most popular interview coding language -->
Programming Language: <%= @interviewee.most_popular_language if @interviewee.most_popular_language  %> <br>
# of Interviews: <%= @interviewee.most_popular_language_count if @interviewee.most_popular_language_count %><br>



<h3>Most Frequent Interviewer:</h3>
<!--Ranks top interviewer based on frequency of interviews -->
Interviewer: <%= @interviewee.most_popular_interviewer %><br>
# of Interviews: <%= @interviewee.most_popular_interviewer_count %><br>