config/routes.rb
Rails.application.routes.draw do
  resources :interview_types
  resources :languages
  resources :appointments
  resources :interviewees
  resources :interviewers
  get '/homepages', to: 'homepages#index', as: 'welcome'
  delete '/sessions/logout_interviewee', to: 'sessions#logout_interviewee', as: 'logout_interviewee'
  get '/sessions/new', to: 'sessions#new', as: 'new_interviewee_login'
  post '/sessions/create', to:'sessions#create', as: 'interviewee_login'
  delete '/sessions/logout_interviewer', to: 'sessions#logout_interviewer', as: 'logout_interviewer'
  get '/sessions/new_int', to: 'sessions#new_int', as: 'new_interviewer_login'
  post '/sessions/create_int', to:'sessions#create_int', as: 'interviewer_login'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/interviewer.rb
class Interviewer < ApplicationRecord
    has_many :appointments
    has_many :interviewees, through: :appointments
    belongs_to :language
    has_secure_password
    validates :username, uniqueness: true
    validates :name, :years_of_experience, :current_company, :current_company, :interview_price, :language_id, presence: true


    def total_money_earned
        no_of_appt = self.appointments.count{|appt| appt if appt.interviewer == self}
        self.interview_price * no_of_appt
    end

    def prog_language
        self.language.prog_lang
    end
    
    def upcoming_appt_times
        appts = self.appointments.select{|appt| appt if appt.interviewer == self}
    end






end

app/controllers/interviewers_controller.rb
class InterviewersController < ApplicationController
    before_action :find_interviewer, only: [:show, :edit, :update, :destroy]
    skip_before_action :authorize_interviewee


    def index
        @interviewers = Interviewer.all
    end

    def show

    end

    def new
        @interviewer = Interviewer.new
        @languages = Language.all
    end
    
    def create
        @interviewer = Interviewer.create(interviewer_params)
        if @interviewer.valid?
            session[:interviewer_id] = @interviewer.id
            redirect_to interviewer_path(@interviewer)
        else
            flash[:my_errors] = @interviewer.errors.full_messages
            render :new
        end
    end

    def edit

    end

    def update
        @interviewer.update(interviewer_params)
        redirect_to interviewer_path(@interviewer)
    end

    def destroy
        @interviewer.destroy
        redirect_to welcome_path
    end

    private

    def interviewer_params
        params.require(:interviewer).permit(:name, :current_role, :current_company, :years_of_experience, :interview_price, :language_id, :username, :password)
    end

    def find_interviewer
        @interviewer = Interviewer.find(params[:id])
    end


end

app/helpers/interviewers_helper.rb
module InterviewersHelper
end

app/views/interviewers/_form.html.erb
<% if flash[:my_errors] %>
    <% flash[:my_errors].each do |err| %>
        Error Message: <%= err %><br>
    <% end %>
<% end %>


<%= bootstrap_form_for(@interviewer, layout: :inline) do |f| %>
    <%= f.text_field :name %><br>
    <br>
    <%= f.text_field :username %><br>
    <br>
    <%= f.text_field :password %><br>
    <br>
    <%= f.text_field :current_role %><br>
    <br>
    <%= f.text_field :current_company %><br>
    <br>
    <%= f.number_field :years_of_experience %><br>
    <br>
    <%= f.collection_select :language_id, Language.all, :id, :prog_lang %><br>
    <br>
    <%= f.number_field :interview_price %><br>
    <br>
    <button type="submit" class="btn btn-primary mb-2">Submit</button>
<% end %>

app/views/interviewers/edit.html.erb
<h1>Join the Interviewer Profile</h1>

<%= render "form"%>

app/views/interviewers/index.html.erb
<h1>Interviewer Home Page</h1>

<%= button_to "Schedule an Appointment", new_appointment_path, method: :get %>

<% @interviewers.each do |interviewer| %>
    <h3>Interviewer Profile</h3>
    Name: <%= link_to interviewer.name, interviewer_path(interviewer) %><br>
    Current Role: <%= interviewer.current_role %><br>
    Current Company: <%= interviewer.current_company %><br>
    Years of Experience: <%= interviewer.years_of_experience %><br>
    Programming Language: <%=interviewer.prog_language%><br>
    Interview Price: $<%= interviewer.interview_price %><br>
    Number of Clients Interviewed: <%= interviewer.interviewees.count %>

<% end %>

app/views/interviewers/new.html.erb
<h1>Join the Interviewer Network</h1>

<%= render "form"%>

app/views/interviewers/show.html.erb
<h1><%=@interviewer.name%>'s Profile Page</h1>

<h3>Actions</h3>
Update Profile Information: <%= button_to "Edit Profile", edit_interviewer_path(@interviewer), method: :get%><br>

Log-out from Application:<%= button_to "Log-out", logout_interviewer_path(@interviewer), method: :delete%><br>

Delete Profile: <%= button_to "Delete Profile Permanently", interviewer_path(@interviewer), method: :delete%><br> 


<h3>Profile Details:</h3>
Name: <%= @interviewer.name %><br>
Years of Experience: <%= @interviewer.years_of_experience %><br>
Current Role: <%= @interviewer.current_role %><br>
Current Company: <%= @interviewer.current_company %><br>
Programming Language: <%= @interviewer.prog_language %><br>
Interview Price: $<%= @interviewer.interview_price %><br>


<h3>My Upcoming Interviews:</h3>
<h4>Appointment Summary</h4>
<% @interviewer.upcoming_appt_times.each do |appt| %>
    <%= appt.interviewee.name %><br>
    <%= appt.date_clean %><br>
    <%= appt.int_type %><br>
<% end %>


<h3>Total Money Earned To Date:</h3>
$<%= @interviewer.total_money_earned %>